name: CI

on:
  push:
  pull_request:


env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # pin@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # pin@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy --all-targets

      - name: Build Documentation
        run: cargo doc --no-deps

      - name: Run tests
        run: cargo test
